### ISSUE TITLE
Refactor to avoid using `setNativeProps`

### ISSUE THREAD

**Issue by JoelRummel** [nithinpp69/react-native-circular-progress-indicator#14]
`setNativeProps` is [not implemented in `react-native-web`](https://github.com/necolas/react-native-web/issues/1935), and it [causes performance bottlenecks with frequent re-renders](https://reactnative.dev/docs/direct-manipulation) (which is common in this type of progress indicator). This module should be refactored to avoid using the `setNativeProps` API.

**Comment by nithinpp69** [comment]
A lot of changes has been introduced in the lib since v1. reopen this ticket if this still needs attention
