### ISSUE TITLE
Refresh animation

### ISSUE THREAD

**Issue by sleaper** [nithinpp69/react-native-circular-progress-indicator#32]
Is there some way how to refresh the countdown animation or I just have to re-render my component?

**Comment by jakrim** [comment]
I'm also wondering this -> I'm setting "count" and trying to increment it -> It's not working

**Comment by nithinpp69** [comment]
Please check https://github.com/nithinpp69/react-native-circular-progress-indicator#play-pause-and-reanimate. This is available from V4.4.0.
