### ISSUE TITLE
Parameter 'props' implicitly has an 'any' type

### ISSUE THREAD

**Issue by erksch** [nithinpp69/react-native-circular-progress-indicator#36]
After including your project, a typecheck fails (even with `--skipLibCheck`):

``` 
node_modules/react-native-circular-progress-indicator/src/circularProgress/index.tsx:184:31 - error TS7006: Parameter 'props' implicitly has an 'any' type.

184 export const dynamicStyles = (props) => {
                                  ~~~~~
Found 1 error.
``` 

You can either fix your implicit `any`s or compile your project to a type definition and commonjs source and publish that instead of the plain typescript source.

**Comment by nithinpp69** [comment]
Thanks for reporting this. The lib is now published as a commonjs source and type definitions with the help of `react-native-builder-bob` starting from `v4.0.0`.
