### ISSUE TITLE
How to display a decimal place value????

### ISSUE THREAD

**Issue by dcc82** [nithinpp69/react-native-circular-progress-indicator#38]

**Comment by dcc82** [comment]
At the moment, I go to index.tsx line 80, then changed it to return `${valuePrefix}${Math.round(animatedValue.value *** 10) / 10**}${valueSuffix}`;
Question: is it possible to add a new prop for the decimal digits?

**Comment by nithinpp69** [comment]
You can add custom progress formats with https://github.com/nithinpp69/react-native-circular-progress-indicator#custom-progress-formatter-function. 
#40 adds a new props progress progressFormatter
Will be available from V2.0.7
