### ISSUE TITLE
Circular progress bar with color change based on value

### ISSUE THREAD

**Issue by Don-Cryptus** [nithinpp69/react-native-circular-progress-indicator#51]
is it possible to change the color based on value with an animation like this?

https://codepen.io/matousek/pen/LZEyQa

**Comment by goxr3plus** [comment]
Wow nice feature i like it !

**Comment by nithinpp69** [comment]
finally landed the feature https://github.com/nithinpp69/react-native-circular-progress-indicator/tree/develop#animated-stroke-color. Please check the API and let me know your thoughts.

**Comment by goxr3plus** [comment]
> finally landed the feature [Animated Stroke Color](https://github.com/nithinpp69/react-native-circular-progress-indicator/tree/develop#animated-stroke-color) Please check the API and let me know your thoughts.

Amazing thanks a lot ♥.

**Comment by nithinpp69** [comment]
New version landed on [NPM V4.3.0](https://www.npmjs.com/package/react-native-circular-progress-indicator/v/4.3.0).
