### ISSUE TITLE
Remove extra padding from svg element container

### ISSUE THREAD

**Issue by rafael-fecha** [nithinpp69/react-native-circular-progress-indicator#53]
When using the circular progress container we can see that the element has it's own padding. Can we remove this or add a prop to customize container styles ?

<img width="155" alt="image" src="https://user-images.githubusercontent.com/37959386/163211444-d1241d5b-caa3-45fd-941c-80e3ba83f1d6.png">

**Comment by rafael-fecha** [comment]
actually it looks like this is not a padding, when I play around with the strokeWidth it increases or decreases the padding from the container view. But I'd expect that the all view size view would be just the size of the svg itself.

**Comment by nithinpp69** [comment]
[71437a2](https://github.com/nithinpp69/react-native-circular-progress-indicator/commit/71437a2fd85aa1f188eda7c950cefce3e1e6485f) fixes this. Will be available in the next release. 
![Screenshot 2022-04-18 at 3 15 56 PM](https://user-images.githubusercontent.com/37703642/163790672-4aca844e-8146-4250-9897-5c009db5a236.png)
