### ISSUE TITLE
Scalable font

### ISSUE THREAD

**Issue by Tadejo9** [nithinpp69/react-native-circular-progress-indicator#54]
Hey,

First of all, great library, I love it!.

Now to the question...is font scaling enabled for title, value and subtitle? Because i would like to have fixed size font, independent of system scaling. Is this possible using this library? It works great on iOS i have issues on Android.

**Comment by nithinpp69** [comment]
Font scaling is enabled by default. There are no props to control this at the moment. We can add a new prop `allowFontScaling` to the progress component and pass it down to the underlying `Text` and `TextInput` components to make this happen. Also what are the issues you are facing on Android?.  🙂

**Comment by nithinpp69** [comment]
https://github.com/nithinpp69/react-native-circular-progress-indicator/commit/71437a2fd85aa1f188eda7c950cefce3e1e6485f fixes this. Added a new prop `allowFontScaling`. Pass this as false to disable font scaling. Will be available in the next release

**Comment by Tadejo9** [comment]
I've tested released version and it works great. Thanks!
