### ISSUE TITLE
[Help] Adding a thumb

### ISSUE THREAD

**Issue by OmkarK45** [nithinpp69/react-native-circular-progress-indicator#59]
Thanks a lot for creating this library! 
I was thinking about how to go about adding a thumb at the end of the progress bar. Is there way to target the last piece of progress so I can attach a thumb? 

![image](https://user-images.githubusercontent.com/45557594/165025501-2cf2551c-1b77-4148-9951-fb42e1b590b6.png)

**Comment by nithinpp69** [comment]
This library doesn't support adding a thumb at the moment.  From your screenshot, I think you can make it happen with [react-native-circular-progress](https://www.npmjs.com/package/react-native-circular-progress) library.

**Comment by OmkarK45** [comment]
Alright! No worries.
