### ISSUE TITLE
[Help] add a user id to value

### ISSUE THREAD

**Issue by bsms66366** [nithinpp69/react-native-circular-progress-indicator#60]
Hi is there any way to add a user id integer from an api fetch as a json key, from an object into the value of the progress circle, instead of having a fixed number, as i'm trying to get a tally of results from a database table to show as a percentage progress (i.e. attendance results ).
any help or advice would be much appreciated.

**Comment by nithinpp69** [comment]
You can completely customise the progress value element by attaching a prefix, suffix etc. Or in your case, If I understood it correctly, you can do the calculations beforehand and then supply the value to the progress circle. Or you can use the `CircularProgressBase` component to render a totally custom child.

**Comment by nithinpp69** [comment]
Closing as no further activity is recorded. Please feel free to reopen if you think this is still an issue.
