### ISSUE TITLE
Children component not being rendered

### ISSUE THREAD

**Issue by lidslira** [nithinpp69/react-native-circular-progress-indicator#63]
I'm trying to insert an icon inside the progress circle, but the component isn't being rendered. Am I doing sth wrong? My code is like:

    <CircularProgressBase
        radius={15}
        activeStrokeColor={colors.primary}
        circleBackgroundColor={'transparent'}
        activeStrokeWidth={3}
        inActiveStrokeWidth={1}
        inActiveStrokeOpacity={0.2}
        value={downloadProgress}
        showProgressValue={false} 
    > 
    { <TouchableOpacity> 
          <CustomIcon 
            style={{ color: colors.primary }}
            name={'stop'} 
            size={10} type={'Ionicons'} 
          />
      </TouchableOpacity> 
    } </CircularProgressBase>

**Comment by nithinpp69** [comment]
I don't see any issue in your code. Are you sure you are importing the component like 
```
import { CircularProgressBase } from 'react-native-circular-progress-indicator';
```
and not
```
import  CircularProgressBase from 'react-native-circular-progress-indicator';
```
