### ISSUE TITLE
Style props for prefix and suffix

### ISSUE THREAD

**Issue by Demetre** [nithinpp69/react-native-circular-progress-indicator#64]
This is an absolutely amazing library, it was so easy to get going, very well documented. I love it! ❤️ ❤️❤️

Just one little question? 

Are there any props to target the prefix and/or suffix strings, similar to progressValueStyle

I'm trying to achieve the effect shown on the attached design, the suffix( s ) is much smaller in comparison to the timer( 45 ) font size.

Thank you again for all your hard work. 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/1145792/169097765-5743ab88-3bbb-4aec-8a50-fa1b9805a7e2.png">

**Comment by nithinpp69** [comment]
Hey Demetre, currently there are no props to customize the prefix/suffix. It inherits the style from the progressValueStyle. We can render the prefix and suffix as separate `Text` components and assign separate styles to it for this use case. But the progress component doesn't have that implemented yet. I'll try to see if I can find some time to work on it today.

**Comment by nithinpp69** [comment]
A new release has been published with this feature [V4.2.0](https://www.npmjs.com/package/react-native-circular-progress-indicator/v/4.2.0) 🎉. The props details are documented at https://github.com/nithinpp69/react-native-circular-progress-indicator#circularprogress-props
