### ISSUE TITLE
Can I pause/ resume

### ISSUE THREAD

**Issue by sabirmgd** [nithinpp69/react-native-circular-progress-indicator#65]
Can we have an abstracted way to pause/resume the animation?

**Comment by nithinpp69** [comment]
The animation cannot be paused/resumed as of now. But this is pretty much doable with the help of `react-native-redash
`

**Comment by nithinpp69** [comment]
Please check https://github.com/nithinpp69/react-native-circular-progress-indicator#play-pause-and-reanimate. This is available from V4.4.0.
