### ISSUE TITLE
node modules error 

### ISSUE THREAD

**Issue by Sarankumr** [nithinpp69/react-native-circular-progress-indicator#67]
![simulator_screenshot_94413A11-4E8A-4310-9D2D-C59324AE6E53](https://user-images.githubusercontent.com/97873029/171951650-7eb1247b-d025-49a9-b8f3-a072f288e004.png)
i cant use this package component when is use this package component i am getting this error

**Comment by nithinpp69** [comment]
Please install the required dependencies. This package has a peer dependency on `react-native-reanimated` and `react-native-svg`. Refer the readme installation guide for more details.

**Comment by nithinpp69** [comment]
Closing as inactive.
