### ISSUE TITLE
strokeColorConfig is making the app crash

### ISSUE THREAD

**Issue by DeepikaSharma5** [nithinpp69/react-native-circular-progress-indicator#82]
The option '`**strokeColorConfig**`' is not working as expected. I have used the same code in the documentation. But when I add the `**strokeColorConfig** `the app is crashing with out any warning or error message. Once I remove that the progress is working.

I am testing in Android. (Still haven't checked in iOS)

If it's an issue please solve this as soon as possible. Or if there are any solutions please provide that

**Comment by jaexplorer** [comment]
I'm still having this issue on latest
