### ISSUE TITLE
react-native-redash dependency is too permissive (comment)

### ISSUE THREAD

**Issue by ajp8164** [nithinpp69/react-native-circular-progress-indicator#89]
My app has installed redash v12.x which does not include `withPause` leading to `undefined is not a function` from  useAnimation.ts. I had to explicitly install the latest version (v18.x) of redash. This may help someone else :-)

**Comment by nithinpp69** [comment]
Probably a good idea to add this in the Readme as well.  https://github.com/nithinpp69/react-native-circular-progress-indicator#prerequisites
